jks = [
    { title: "Hk解析", url: "http://jx.rdhk.net/?v=" },
    { title: "小蒋极致", url: "https://www.kpezp.cn/jlexi.php?url=" },
    { title: "维多解析（超清）", url: "https://jx.ivito.cn/?url=" },
    { title: "智库解析", url: "http://www.guandianzhiku.com/v/s/?url=" },
    { title: "逆天解析", url: "http://nitian9.com/?url=" },
    { title: "解析系统", url: "https://www.ckmov.vip/api.php?url=" },
    { title: "bl解析", url: "https://vip.bljiex.com/?v=" },
    { title: "凉城解析", url: "http://jx.mw0.cc/?url=" },
    { title: "宏伟解析", url: "http://www.cqhwdnwx.com/jx/?url=" },
    { title: "116kan", url: "http://vip.116kan.com/?url=" },
    { title: "弦易阁", url: "http://jx.hongyishuzhai.com/index.php?url=" },
    { title: "55解析", url: "http://55jx.top/?url=" },
    { title: "19解析", url: "http://19g.top/?url=" },
    { title: "热点解析", url: "http://jx.rdhk.net/?v=" },
    { title: "ha12解析", url: "http://py.ha12.xyz/sos/index.php?url=" },
    { title: "云解析", url: "http://gege.ha123.club/gege1234/index.php?url=" },
    { url: "http://www.1717yun.com/jx/ty.php?url=", title: "通用vip接口3" },
    { url: "http://py.ha12.xyz/sos/index.php?url=", title: "玩的嗨——41-若接口失效可反馈！QQ群:340569308" },
    { url: "http://jx.618ge.com/?url=", title: "玩的嗨——34-若接口失效可反馈！QQ群:340569308" },

    { url: "http://jx.13tv.top/?url=", title: "①号引擎系统【推荐】" },
    { url: "http://api.13tv.top/jiexi/?url=", title: "②号引擎系统【推荐】" },
    { url: "https://www.cuan.la/m3u8.php?url=", title: "③号接口-B站专用接口" },
    { url: "https://jx.m3u8.tv/jiexi/?url=", title: "⑤号接口" },
    { url: "http://17kyun.com/api.php?url=", title: "17云" },

    { url: "http://www.1717yun.com/jx/ty.php?url=", title: "玩的嗨——24-若接口失效可反馈！QQ群:340569308" },
    { url: "https://player.baodai.org/ipsign/player.php?v=", title: "玩的嗨——23-若接口失效可反馈！QQ群:340569308" },
    { url: "http://17kyun.com/api.php?url=", title: "玩的嗨——16-若接口失效可反馈！QQ群:340569308" },
    { url: "https://www.1717yun.com/jx/ty.php?url=", title: "玩的嗨——46-若接口失效可反馈！QQ群:340569308" },
    { url: "https://z1.m1907.cn/?jx=", title: "玩的嗨——28-若接口失效可反馈！QQ群:340569308" },
    { url: "https://jx.70808.net/?url=", title: "玩的嗨——56-若接口失效可反馈！QQ群:340569308" },
    { url: "http://vip.wandhi.com/?v=", title: "玩的嗨——45-若接口失效可反馈！QQ群:340569308" },
];